FROM ruby:2.7.4-alpine3.13

ENV APP_ROOT /var/www/tidyoffice

ADD . $APP_ROOT
WORKDIR $APP_ROOT

RUN apk add --no-cache build-base tzdata \
  && wget ftp://ftp.freetds.org/pub/freetds/stable/freetds-1.3.3.tar.gz && \
  	tar -xzf freetds-1.3.3.tar.gz && \
  	cd freetds-1.3.3 && \
  	sh ./configure --prefix=/usr/local --with-tdsver=7.3 && \
  	make && \
  	make install \
	&& ln -snf /usr/share/zoneinfo/Asia/Irkutsk /etc/localtime && echo Asia/Irkutsk > /etc/timezone \
  && bundle install